name: pizza_server
description: Dart shelf backend for PizzaF ordering app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.11.5

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  dart_jsonwebtoken: ^3.4.1
  crypto: ^3.0.0
  uuid: ^4.0.0
  args: ^2.0.0
  shared:
    path: ../shared

dev_dependencies:
  lints: ^5.1.0
